"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost, 127.0.0.1").split()


# Application definition

INSTALLED_APPS = [

     # media modules
    "cloudinary",
    'django.contrib.staticfiles',
    "cloudinary_storage",


    "drf_spectacular",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    "rest_framework",
    "rest_framework_simplejwt",

    # my apps
    "apps.tenants",
    "apps.inventory",
    "apps.orders",
    "apps.users",
    "apps.customers",
    "apps.audit",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
     "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # my middleware
    "apps.tenants.middleware.TenantIsolationMiddleware",
]

# ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config("DB_NAME"),
        "HOST":config("DB_HOST"),
        "USER": config("DB_USER"),
        "PASSWORD":config("DB_PASSWORD"),
        "PORT":config("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
DEFAULT_FILE_STORAGE="cloudinary_storage.storage.MediaCloudinaryStorage"
STATICFILES_STORAGE="whitenoise.storage.StaticFilesStorage"

STORAGES={
    "default":{
        "BACKEND":"cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles":{
        "BACKEND":"whitenoise.storage.StaticFilesStorage"
    },
}

CLOUDINARY_STORAGE={
    "CLOUD_NAME":config("CLOUDINARY_CLOUD_NAME"),
    "API_KEY":config("CLOUDINARY_API_KEY"),
    "API_SECRET":config("CLOUDINARY_API_SECRET"),
}

AUTH_USER_MODEL="tenants.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES":[
        "rest_framework_simplejwt.authentication.JWTAuthentication"
    ],

    "DEFAULT_PERMISSION_CLASSES":[
        "rest_framework.permissions.IsAuthenticated"
    ],

    "DEFAULT_SCHEMA_CLASS":
    "drf_spectacular.openapi.AutoSchema"
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME":timedelta(weeks=4)
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Multi-Tenant SaaS B2B Enterprise Inventory & Order API Engine',
    'DESCRIPTION': 'Headless high-concurrency cloud resource tracking backend infrastructure.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    
    # 🔥 Wire JWT Bearer authentication options cleanly into the UI toolbar
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [{'BearerAuth': []}],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'Input your raw access token string to unlock tenant endpoints.'
            }
        }
    }
}





ROOT_URLCONF = "core.urls"

# Celery Broker and Result Storage Configuration Configurations
CELERY_BROKER_URL = config("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND")

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

